// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdjsomyodshygqutuokh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkanNvbXlvZHNoeWdxdXR1b2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjEwMzksImV4cCI6MjA2NjU5NzAzOX0.nXm5vZwkciZD8K6ak80PGsHdUEbxou8MxPoNwRkG0Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);